abbr -a k kubectl
abbr -a kca '_kca(){ kubectl "$@" --all-namespaces;  unset -f _kca; }; _kca'
abbr -a kaf 'kubectl apply -f'
abbr -a keti 'kubectl exec -t -i'
abbr -a kcuc 'kubectl config use-context'
abbr -a kcsc 'kubectl config set-context'
abbr -a kcdc 'kubectl config delete-context'
abbr -a kccc 'kubectl config current-context'
abbr -a kcgc 'kubectl config get-contexts'
abbr -a kdel 'kubectl delete'
abbr -a kdelf 'kubectl delete -f'
abbr -a kgp 'kubectl get pods'
abbr -a kgpa 'kubectl get pods --all-namespaces'
abbr -a kgpw 'kgp --watch'
abbr -a kgpwide 'kgp -o wide'
abbr -a kep 'kubectl edit pods'
abbr -a kdp 'kubectl describe pods'
abbr -a kdelp 'kubectl delete pods'
abbr -a kgpall 'kubectl get pods --all-namespaces -o wide'
abbr -a kgpl 'kgp -l'
abbr -a kgpn 'kgp -n'
abbr -a kgs 'kubectl get svc'
abbr -a kgsa 'kubectl get svc --all-namespaces'
abbr -a kgsw 'kgs --watch'
abbr -a kgswide 'kgs -o wide'
abbr -a kes 'kubectl edit svc'
abbr -a kds 'kubectl describe svc'
abbr -a kdels 'kubectl delete svc'
abbr -a kgi 'kubectl get ingress'
abbr -a kgia 'kubectl get ingress --all-namespaces'
abbr -a kei 'kubectl edit ingress'
abbr -a kdi 'kubectl describe ingress'
abbr -a kdeli 'kubectl delete ingress'
abbr -a kgns 'kubectl get namespaces'
abbr -a kens 'kubectl edit namespace'
abbr -a kdns 'kubectl describe namespace'
abbr -a kdelns 'kubectl delete namespace'
abbr -a kcn 'kubectl config set-context --current --namespace'
abbr -a kgcm 'kubectl get configmaps'
abbr -a kgcma 'kubectl get configmaps --all-namespaces'
abbr -a kecm 'kubectl edit configmap'
abbr -a kdcm 'kubectl describe configmap'
abbr -a kdelcm 'kubectl delete configmap'
abbr -a kgsec 'kubectl get secret'
abbr -a kgseca 'kubectl get secret --all-namespaces'
abbr -a kdsec 'kubectl describe secret'
abbr -a kdelsec 'kubectl delete secret'
abbr -a kgd 'kubectl get deployment'
abbr -a kgda 'kubectl get deployment --all-namespaces'
abbr -a kgdw 'kgd --watch'
abbr -a kgdwide 'kgd -o wide'
abbr -a ked 'kubectl edit deployment'
abbr -a kdd 'kubectl describe deployment'
abbr -a kdeld 'kubectl delete deployment'
abbr -a ksd 'kubectl scale deployment'
abbr -a krsd 'kubectl rollout status deployment'
abbr -a kgrs 'kubectl get replicaset'
abbr -a kdrs 'kubectl describe replicaset'
abbr -a kers 'kubectl edit replicaset'
abbr -a krh 'kubectl rollout history'
abbr -a kru 'kubectl rollout undo'
abbr -a kgss 'kubectl get statefulset'
abbr -a kgssa 'kubectl get statefulset --all-namespaces'
abbr -a kgssw 'kgss --watch'
abbr -a kgsswide 'kgss -o wide'
abbr -a kess 'kubectl edit statefulset'
abbr -a kdss 'kubectl describe statefulset'
abbr -a kdelss 'kubectl delete statefulset'
abbr -a ksss 'kubectl scale statefulset'
abbr -a krsss 'kubectl rollout status statefulset'
abbr -a kpf "kubectl port-forward"
abbr -a kga 'kubectl get all'
abbr -a kgaa 'kubectl get all --all-namespaces'
abbr -a kl 'kubectl logs'
abbr -a kl1h 'kubectl logs --since 1h'
abbr -a kl1m 'kubectl logs --since 1m'
abbr -a kl1s 'kubectl logs --since 1s'
abbr -a klf 'kubectl logs -f'
abbr -a klf1h 'kubectl logs --since 1h -f'
abbr -a klf1m 'kubectl logs --since 1m -f'
abbr -a klf1s 'kubectl logs --since 1s -f'
abbr -a kcp 'kubectl cp'
abbr -a kgno 'kubectl get nodes'
abbr -a keno 'kubectl edit node'
abbr -a kdno 'kubectl describe node'
abbr -a kdelno 'kubectl delete node'
abbr -a kgpvc 'kubectl get pvc'
abbr -a kgpvca 'kubectl get pvc --all-namespaces'
abbr -a kgpvcw 'kgpvc --watch'
abbr -a kepvc 'kubectl edit pvc'
abbr -a kdpvc 'kubectl describe pvc'
abbr -a kdelpvc 'kubectl delete pvc'
abbr -a kdsa "kubectl describe sa"
abbr -a kdelsa "kubectl delete sa"
abbr -a kgds 'kubectl get daemonset'
abbr -a kgdsw 'kgds --watch'
abbr -a keds 'kubectl edit daemonset'
abbr -a kdds 'kubectl describe daemonset'
abbr -a kdelds 'kubectl delete daemonset'
abbr -a kgcj 'kubectl get cronjob'
abbr -a kecj 'kubectl edit cronjob'
abbr -a kdcj 'kubectl describe cronjob'
abbr -a kdelcj 'kubectl delete cronjob'
abbr -a kgj 'kubectl get job'
abbr -a kej 'kubectl edit job'
abbr -a kdj 'kubectl describe job'
abbr -a kdelj 'kubectl delete job'
