#!/bin/bash
# vi: ft=sh

# # Ensure /etc/resolv.conf is a regular file we can overwrite
# if [ -L /etc/resolv.conf ]; then
#   rm -f /etc/resolv.conf
# fi

echo "nameserver 8.8.8.8" >/etc/resolv.conf
